// <auto-generated />
using System;
using Infraesctructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraesctructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240827210453_MyMigration")]
    partial class MyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("CartId");

                    b.HasIndex("ClientId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("DNI")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("ClientId");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Apellido = "Vitek",
                            DNI = 23344312,
                            Direccion = "Bynnon 2331",
                            Nombre = "Nicolas",
                            Telefono = "4234-1231"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<double>("Total")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CartId")
                        .IsUnique();

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Codigo = "a-043",
                            Descripcion = "40 grm",
                            Image = "Http://static.cotodigital3.com.ar/sitios/fotos/full/00523500/00523588.jpg?3.0.138f",
                            Marca = "Sol Serrano",
                            Nombre = "Alfajor",
                            Precio = 37.990000000000002
                        },
                        new
                        {
                            ProductId = 2,
                            Codigo = "a-099",
                            Descripcion = "Edicion 1950, 1 kgrm",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00510600/00510606.jpg?3.0.138f",
                            Marca = "Amanda",
                            Nombre = "Yerba mate",
                            Precio = 543.33000000000004
                        },
                        new
                        {
                            ProductId = 3,
                            Codigo = "a-007",
                            Descripcion = "520 grm",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00263300/00263369.jpg?3.0.138f",
                            Marca = "Corper",
                            Nombre = "Pure de tomate",
                            Precio = 95.400000000000006
                        },
                        new
                        {
                            ProductId = 4,
                            Codigo = "a-211",
                            Descripcion = "20 grm",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00230100/00230124.jpg?3.0.138f",
                            Marca = "La Virginia",
                            Nombre = "Cafe molido",
                            Precio = 388.14999999999998
                        },
                        new
                        {
                            ProductId = 5,
                            Codigo = "a-055",
                            Descripcion = "Bajo en sodio, 340 grm",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00537400/00537472.jpg?3.0.138f",
                            Marca = "Doña Pupa",
                            Nombre = "Arvejas",
                            Precio = 65.390000000000001
                        },
                        new
                        {
                            ProductId = 6,
                            Codigo = "b-013",
                            Descripcion = "Sin gas, 2.5 lt",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00289600/00289636.jpg?3.0.138f",
                            Marca = "Bonaqua",
                            Nombre = "Agua mineral",
                            Precio = 91.709999999999994
                        },
                        new
                        {
                            ProductId = 7,
                            Codigo = "b-020",
                            Descripcion = "Light, 2 lt",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00189500/00189594.jpg?3.0.138f",
                            Marca = "Coca-Cola",
                            Nombre = "Gaseosa",
                            Precio = 134.55000000000001
                        },
                        new
                        {
                            ProductId = 8,
                            Codigo = "f-103",
                            Descripcion = "Entera, sache 1 lt",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00170500/00170599.jpg?3.0.138f",
                            Marca = "La Serenisima",
                            Nombre = "Leche",
                            Precio = 183.25
                        },
                        new
                        {
                            ProductId = 9,
                            Codigo = "c-017",
                            Descripcion = "Caja 160 grm",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00499100/00499140.jpg?3.0.138f",
                            Marca = "Fudy",
                            Nombre = "Cookie Sandwich",
                            Precio = 259.0
                        },
                        new
                        {
                            ProductId = 10,
                            Codigo = "l-022",
                            Descripcion = "Doble hoja, caja 100u",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00264600/00264677.jpg?3.0.138f",
                            Marca = "Elite",
                            Nombre = "Pañuelos",
                            Precio = 149.87
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductCart", b =>
                {
                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCart", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Cart", b =>
                {
                    b.HasOne("Domain.Entities.Client", "Client")
                        .WithMany("Cart")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.Cart", "Cart")
                        .WithOne("Order")
                        .HasForeignKey("Domain.Entities.Order", "CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Domain.Entities.ProductCart", b =>
                {
                    b.HasOne("Domain.Entities.Cart", "Cart")
                        .WithMany("ProductCart")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ProductCart")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Cart", b =>
                {
                    b.Navigation("Order")
                        .IsRequired();

                    b.Navigation("ProductCart");
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductCart");
                });
#pragma warning restore 612, 618
        }
    }
}
